#!/bin/sh
set -e

if [ -f /etc/default/balrog]; then
    . /etc/default/balrog
fi

if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
    rm -rf /var/run/balrog
    rm -rf /var/log/balrog

    if id -u balrogd >/dev/null 2>&1; then
        userdel -r balrogd || true
    fi

    if getent group balrogd >/dev/null 2>&1; then
        groupdel balrogd || true
    fi

    # delete balrog udev rules
    if [ -f "$UDEV_RULES_PATH"]; then
        rm -f "$UDEV_RULES_PATH"
    fi
fi

if [ "$1" = "purge" ]; then
    rm -rf /var/run/balrog
    rm -rf /var/log/balrog
fi

exit 0

