#!/bin/sh
set -e

reload_udev_rules() {
    echo Reloading udev rules
    if ! udevadm control --reload > /dev/null 2>&1; then
        echo "Reload fail"
        echo "You may want try to execute \"udevadm control --reload\" or reboot your system"
    fi
    echo done
}

if [ -f /etc/default/balrog]; then
    . /etc/default/balrog
fi

if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
    rm -rf /var/run/balrog
    rm -rf /var/log/balrog
    rm -rf "$UDEV_RULES_PATH"
    reload_udev_rules

    if id -u balrogd >/dev/null 2>&1; then
        userdel -r balrogd || true
    fi

    if getent group balrogd >/dev/null 2>&1; then
        groupdel balrogd || true
    fi

    # delete balrog udev rules
    if [ -f "$UDEV_RULES_PATH"]; then
        rm -f "$UDEV_RULES_PATH"
    fi
fi

if [ "$1" = "purge" ]; then
    rm -rf /var/run/balrog
    rm -rf /var/log/balrog
fi

exit 0

